PREFIX dc:   <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?publisher (COUNT(DISTINCT ?asset) AS ?assets)
WHERE {
  ?asset dc:publisher ?pub .
  OPTIONAL {
    ?pub rdfs:label ?lbl .
    FILTER(LANG(?lbl) = "" || LANGMATCHES(LANG(?lbl), "en"))
  }
  BIND(COALESCE(?lbl, STR(?pub)) AS ?publisher)
}
GROUP BY ?publisher
ORDER BY DESC(?assets)